stages:

  download_external_dataset:
    cmd: python3 src/data/download_dataset.py data/external/face-mask-detection
    deps:
      - src/data/download_dataset.py
    outs:
      - data/external/face-mask-detection

  make_dataset_external:
    cmd: python3 src/data/make_dataset.py data/external/face-mask-detection/annotations data/interim/annotations.csv
    deps:
      - data/external/face-mask-detection/annotations
      - src/data/make_dataset.py
    outs:
      - data/interim/annotations.csv

  create_crop_dataset_external:
    cmd: python3 src/data/create_crop_dataset.py data/interim/annotations.csv  data/external/face-mask-detection/images/  data/processed/cropped_images/
    deps:
      - data/interim/annotations.csv
      - data/external/face-mask-detection/images
      - src/data/create_crop_dataset.py
    outs:
      - data/processed/cropped_images

  merge_datasets:
    cmd: python3 src/data/mix_datasets.py data/raw/raw_data/ data/processed/cropped_images/ data/processed/unsplit_train_data/
    deps:
      - data/raw/raw_data/
      - data/processed/cropped_images/
      - src/data/mix_datasets.py
    outs:
      - data/processed/unsplit_train_data/

  train_test_split:
    foreach:
      - input_path: data/raw/raw_data/
        data_type: internal
      - input_path: data/processed/cropped_images/
        data_type: external
      - input_path: data/processed/unsplit_train_data/
        data_type: both
    do:
      cmd: python3 src/models/train_test_split.py ${item.input_path} ${item.data_type} data/processed/train_data_${item.data_type}/
      deps:
        - ${item.input_path}
        - src/models/train_test_split.py
      outs:
        - data/processed/train_data_${item.data_type}/

  train_model:
    foreach:
      - dataset_path: data/processed/train_data_internal/
        data_type: internal
      - dataset_path: data/processed/train_data_external/
        data_type: external
      - dataset_path: data/processed/train_data_both
        data_type: both
    do:
      cmd: python3 src/models/train.py  ${item.dataset_path} ${item.data_type} src/models/configs/nn_config.yaml models/nn_model_${item.data_type}
      deps:
        - ${item.dataset_path}
        - src/models/configs/nn_config.yaml
        - src/models/train.py
      outs:
        - models/nn_model_${item.data_type}

  validate_model:
    foreach:
      - dataset_path: data/processed/train_data_internal/val/
        data_type: internal
      - dataset_path: data/processed/train_data_external/val/
        data_type: external
      - dataset_path: data/processed/train_data_both/val/
        data_type: external
    do:
      cmd: python3 src/models/validate.py  models/nn_model_${item.data_type}/data/model.pth ${item.dataset_path} ${item.data_type} src/models/configs/nn_config.yaml
      deps:
        - models/nn_model_${item.data_type}/data/model.pth
        - ${item.dataset_path}
        - src/models/configs/nn_config.yaml

#

