#возможные модели vit_timm, resnet, mobilenet
model_name: 'resnet'
pretrained: true
num_classes: 2
batch_size: 16
num_epochs: 1
criterion: 'cross_entropy_loss'
optimizer: 'adam'
scheduler: 'multistep_lr'