#возможные модели vit_timm, resnet, mobilenet
model_name: 'vit_timm'
pretrained: true
num_classes: 2
batch_size: 512
num_epochs: 5
criterion: 'cross_entropy_loss'
optimizer: 'sgd'
scheduler: 'step_lr'